---
title: "ANALYSING COUNT DATA 1" 
author: 
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    social: menu
    source_code: embed
runtime: shiny
---
Probability mass functions
===

```{r global, include=FALSE}

  rm(list=ls())
  set.seed(6453)
  library(MASS)      # for neg binomial analysis and correlated data generation
  library(ggplot2)
  library(shiny)
  library(utf8)      # codes for Greek letters
  library(gridExtra)
  library(tidyverse)
 
  lwd.=3             # used when plotting
  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # function to format decimals
  # https://stackoverflow.com/questions/3245862/format-numbers-to-significant-figures-nicely-in-r
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  formatz <- function(x){
    
    if (!is.na(x)  ) {
      
      formatC(signif(x,digits=5), digits=5,format="fg", flag="#",big.mark=",")
      
    }
    
  }
  
  formatz0 <- function(x){
    sprintf(x, fmt = '%s')  
  }
  formatz1 <- function(x){
    sprintf(x, fmt = '%#.1f')  
  }
  formatz2 <- function(x){
    sprintf(x, fmt = '%#.2f')  
  }
  formatz00 <- function(x){
    round(x,0) 
  }
  formatz3 <- function(x){
    sprintf(x, fmt = '%#.3f')  
  }
  formatz4 <- function(x){
    sprintf(x, fmt = '%#.4f')  
  }
  
  
  
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# function for nice upper limits to count bar plots, stack exchange
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
    roundUpNice <- function(x, nice=c(1,1.5, 2,4,5,6,8,10)) { #added 1.5 to help bar plot y scale
    if(length(x) != 1) stop("'x' must be of length 1")
    10^floor(log10(x)) * nice[[which(x <= 10^floor(log10(x)) * nice)[[1]]]]
  }
  
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Define the Negative Binomial probability density function, with parameters
# mu and alpha. The mean of this NB distribution is mu, and variance is sigma^2=mu+alpha*mu^2
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
   e_dnbinom=function(x,mu,alpha){
     
    k = 1/alpha
    s1 = lgamma(k+x)-lgamma(k)-lgamma(x+1)    # lgamma is log(gamma)
    s2 = x*log(mu/(mu+k))
    s3 = -k*log(1+mu/k)
    prob = exp(s1+s2+s3)
    prob[x<0] = 0
    prob[prob>1] = 1
    prob[prob<0] = 0
    return(prob)
    
  }

# check
# dnbinom(   1, size=2,   mu=3)
# e_dnbinom(1, alpha=1/2,mu=3)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# This function translates the mu and alpha parameters into an alternative
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  e_rnbinom=function(n,mu,alpha){
    size = 1/alpha          # so now we can just enter alpha this is converted to 1/ alpha
    prob = size/(mu+size)   # so now we can enter mu the mean and that is converted to prob
    return(rnbinom(n,size=size,prob=prob))
  }

 
 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# start of app
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Column {.sidebar}
-----------------------------------------------------------------------

**Count data analysis is explored**

```{r tab1}

 
  sliderInput('mu', 'Common  \u03BC', value=1.5,
                min = 1, max = 25, step=.5, ticks=F)
  
  sliderInput('alpha_a', '\u03B1 for red curve', value = c(1.3),
                min = 0, max = 5 ,step=0.01, ticks=F)
  
  sliderInput('alpha_b', '\u03B1 for dark blue curve', value = c(1.3),
                min = 0, max = 5 ,step=0.01, ticks=F)
  
  sliderInput('alpha_d', '\u03B1 for purple curve', value = c(1.3),
                min = 0, max = 5 ,step=0.01, ticks=F)
  
  sliderInput('sims', 'Simulations (chart 2)', 50000,
                min = 50000, max = 500000,step=50000,ticks=F)
  
  sliderInput('x_range', 'Plot x-range', value = c(0,10),
          min = 0, max = 80,step=5,ticks=F)
  
  sliderInput('y_range', 'Plot y-range', value = c(0,.5),
          min = 0, max = 1,step=.05,ticks=F)

  checkboxInput('perc','show stats on barplot', value=TRUE)

```

$\alpha$ takes on positive rational values, rarely above 4. Values of $\alpha$ greater than 2 usually indicate that there is substantial over-dispersion.

When $\alpha$ approaches 0, k approaches infinity and Poisson emerges (move red $\alpha$ slider to 0).

When $\alpha$ > 1, k < 1 leads to over dispersed data.

$\alpha$ = 1/k ; k = 1/ $\alpha$ see next tab.
 

Column {data-width=400, height=300}
-----------------------------------------------------------------------
### Chart 1


```{r tab1 plot1}

renderPlot({

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Cannot find the reference that helped with code in this tab!
# NB density function, and overlay the Poisson distribution with the same mean
# Normal with variance equal to mean also
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
  mu =      input$mu
  alpha_a = input$alpha_a
  alpha_b = input$alpha_b
  alpha_d = input$alpha_d
  low =     input$x_range[1]
  high=     input$x_range[2]
  xmax =    high
  ymax =    input$y_range[2]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # if else to turn neg binomial into poisson if alpha =0
  x=c(-0.0001,seq(0,xmax,1))
  
  y =          dpois(x,mu)
   
  if(alpha_a==0) {
  yb =          dpois(x,mu)
  }else{
  yb=     e_dnbinom(x,mu,alpha_a)
  }
  
  if(alpha_b==0){
  yc =          dpois(x,mu)
  }else{
  yc=     e_dnbinom(x,mu,alpha_b)
  }
  
  if(alpha_d==0){
  yd =          dpois(x,mu)
  }else{
  yd=     e_dnbinom(x,mu,alpha_d)
  }
  
  nor <- dnorm(x, mu, sqrt(mu))
 
  x=  c(0,x)  
  y=  c(0,y)
  yb= c(0,yb)
  yc= c(0,yc)
  yd= c(0,yd)
  nor=c(0,nor)
  
  l = !is.na(y+yb+yc+yd+nor)
  
  plot(x[l],y[l], ylim=c(0,ymax), xlim=c(low,xmax), type="l", lwd=lwd., xlab="x",
       ylab="prob(x)", main="Probability distributions")
  
  lines(x[l],yb[l], col=2,lwd=lwd.,type="l")
  lines(x[l],yc[l], col=4,lwd=lwd.,type="l")
  lines(x[l],nor[l],col=5,lwd=lwd.,type="l")
  lines(x[l],yd[l], col=6,lwd=lwd.,type="l")
   
  apois = paste("Poisson \u03BC=", mu,sep="")
  nb_a =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_a,sep="")
  nb_b =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_b,sep="")
  nb_c =  paste("Normal \u03BC=",   mu," \u03C3=sqrt(",mu,")",sep="")
  nb_d =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_d,sep="")
  
  legend("topright",col=c(1,2,4,6,5),legend=c(apois, nb_a, nb_b, nb_d, nb_c), lwd=lwd.,bty="n")
 }
)

```

### Chart 2

```{r, tab1 plot2}

renderPlot({
  
    n=input$sims
    
    mu = input$mu
    alpha_a =  input$alpha_a
    alpha_b =  input$alpha_b
    alpha_d =  input$alpha_d
    low =      input$x_range[1]
    xmax=      input$x_range[2]
    ymax =     input$y_range[2]
    
    z  =      rpois(n,mu)
    zb = e_rnbinom(n,mu,alpha_a)
    zc = e_rnbinom(n,mu,alpha_b)
    zd =      rnorm(n,mu,sqrt(mu))
    ze = e_rnbinom(n,mu,alpha_d)
    
    a=hist(z, plot=F,breaks=seq(-1.5,n+.5,1))
    b=hist(zb,plot=F,breaks=seq(-1.5,n+.5,1))
    c=hist(zc,plot=F,breaks=seq(-1.5,n+.5,1))
    d=hist(zd,plot=F,breaks=200)
    e=hist(ze,plot=F,breaks=seq(-1.5,n+.5,1))
    
    atitle = paste("Distributions based on",n,"random draws")
    
    plot(a$mids,a$density,type="s",lwd=lwd., col=1, ylim=c(0,ymax),
         main=atitle, xlim=c(low,xmax),
         xlab="x", ylab="Fraction falling within each bin")
    
    lines(b$mids,b$density,type="s",lwd=lwd.,col=2)
    lines(c$mids,c$density,type="s",lwd=lwd.,col=4)
    lines(d$mids,d$density,type="s",lwd=lwd.,col=5)
    lines(e$mids,e$density,type="s",lwd=lwd.,col=6)
    
    apois = paste("Poisson \u03BC="  ,mu,  sep="")
    nb_a =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_a,     sep="")
    nb_b =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_b,     sep="")
    nb_c =  paste("Normal \u03BC=",   mu," \u03C3=sqrt(",mu,")", sep="")
    nb_d =  paste("Neg Binom \u03BC=",mu," \u03B1=",alpha_d,     sep="")
    
    legend("topright",col=c(1,2,4,6,5),legend=c(apois, nb_a, nb_b, nb_d, nb_c),
           lwd=lwd.,bty="n")

})

```

Column {data-width=400}
-------------------------------------

### Chart 3

```{r, tab1 plot3}

renderPlot({
  
  mu = input$mu
  alpha_a = input$alpha_a
  low =  input$x_range[1]
  xmax=  input$x_range[2]
  ymax = input$y_range[2]
  
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  xx <- c(seq(0,xmax,1))

  yb = dpois(xx,mu)
  
  par(mar=c(2.1,4.1,4.1,4.1))
      
  b <- barplot(yb, xlim=c(0,xmax+2), ylab = "Percent", xlab="x", col='black', ylim=c(0,ymax),
          main = paste0("Poisson \u03BC = ", mu, ", based on common \u03BC",sep=""),
          names.arg= as.character(xx))
   
  if(input$perc) {
  x <-0:length(b) #  % onto top of bars
  y1 <- yb + 0.02
  z <- round(yb,2) *100
  z <- paste0(z,"%")
  text(x=b[x+1],y=(y1),labels=z, cex = 1)
  }

})

```

### Chart 4

```{r, tab1 plot4}

    renderPlot({
  
    mu = input$mu
    alpha_a = input$alpha_a
  
    low =  input$x_range[1]
    xmax=  input$x_range[2]
    ymax = input$y_range[2]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  xx <- c(seq(0,xmax,1))

  if(alpha_a==0) {
  yb =    dpois(xx,mu)
  }else{
  yb=     e_dnbinom(xx,mu,alpha_a)
  }
  
  par(mar=c(2.1,4.1,4.1,4.1))
      
  b <- barplot(yb, xlim=c(0,xmax+2), ylab = "Percent", xlab="x", col='red',
          ylim=c(0,ymax),
          main =  paste0("Negative Binomial \u03BC = ",mu," \u03B1 = ",alpha_a,", based on common mean and red curve \u03B1, variance = ", mu+alpha_a*mu^2* alpha_a,""),
          names.arg= as.character(xx))
  
  if(input$perc) {
  x <-0:length(b) # % onto top of bars
  y1 <- yb + 0.02
  z <- round(yb,2) *100
  z <- paste0(z,"%")
  text(x=b[x+1],y=(y1),labels=z, cex = 1)
  }
})

```
 